// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesAnalyticsApi.Data;

#nullable disable

namespace SalesAnalyticsApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesAnalyticsApi.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = "C456",
                            Address = "123 Main St, Anytown, CA 12345",
                            Email = "johnsmith@email.com",
                            Name = "John Smith"
                        },
                        new
                        {
                            CustomerId = "C789",
                            Address = "456 Elm St, Otherville, NY 54321",
                            Email = "emilydavis@email.com",
                            Name = "Emily Davis"
                        },
                        new
                        {
                            CustomerId = "C101",
                            Address = "789 Oak St, New City, TX 75024",
                            Email = "Sarah Johnson",
                            Name = "Sarah Johnson"
                        });
                });

            modelBuilder.Entity("SalesAnalyticsApi.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfSale")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuantitySold")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DateOfSale")
                        .HasDatabaseName("IX_Orders_DateOfSale");

                    b.HasIndex("ProductId");

                    b.HasIndex("DateOfSale", "ProductId")
                        .HasDatabaseName("IX_Orders_DateOfSale_Product");

                    b.HasIndex("DateOfSale", "Region")
                        .HasDatabaseName("IX_Orders_DateOfSale_Region");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SalesAnalyticsApi.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Products_Category");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "P123",
                            Category = "Shoes",
                            Name = "UltraBoost Running Shoes"
                        },
                        new
                        {
                            ProductId = "P456",
                            Category = "Electronics",
                            Name = "iPhone 15 Pro"
                        },
                        new
                        {
                            ProductId = "P789",
                            Category = "Clothing",
                            Name = "Levi's 501 Jeans"
                        },
                        new
                        {
                            ProductId = "P234",
                            Category = "Electronics",
                            Name = "Sony WH-1000XM5 Headphones"
                        });
                });

            modelBuilder.Entity("SalesAnalyticsApi.Models.Order", b =>
                {
                    b.HasOne("SalesAnalyticsApi.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesAnalyticsApi.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesAnalyticsApi.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SalesAnalyticsApi.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
